// auto-generated by Fins.AdminTools.ModelBuilder for table fonts.
inherit Fins.Model.DataObject;

string table_name = "fonts";
string instance_name = "Font";

void post_define(Fins.Model.DataModelContext context)
{
  // Add any post configuration logic here
  // set_alternate_key("myalternatekey");
}
