// auto-generated by Fins.AdminTools.ModelBuilder for table locations.
inherit Fins.Model.DataObject;

string table_name = "locations";
string instance_name = "Location";

void post_define(Fins.Model.DataModelContext context)
{
  // Add any post configuration logic here
  // set_alternate_key("myalternatekey");
}
