<html><head><title>Listing <%$type%></title></head>
  <body>
  <h1><%$type%></h1>
  <div class="flash-message"><% flash var="$msg" %></div>
  <%foreach var="$items" val="item"%> [ 
  <%action_link action="display" id="$item._id"%>view</a> || 
  <%action_link action="update" id="$item._id"%>edit</a> || 
  <%action_link action="delete" id="$item._id"%>delete</a> ] 
  <%describe_object var="$item"%><br/>
  <%end%>
  <p>
  [ <%action_link action="new"%>new</a> ] 
</body></html>
